# Config for billengine

dbDetails:

  hostAddress: 'localhost'

  port: 5432

  user: 'postgres'

  password: '123456'

  database: 'ioenergy'


dataNullValues: ["UNKNOWN"]

testEnv: 'local' 

# local, development, production